version: '3.8'

services:
  carteiras:
    image: masassuncao/sistema-carteira-virtual:latest
    container_name: sistema-carteira-virtual
    network_mode: "host"
    ports:
      - 3000:3000
    environment:
      - ENDERECO_HOST_MQ=${ENDERECO_HOST_MQ}

  usuarios:
    image: masassuncao/sistema-cadastro-usuarios:latest
    container_name: sistema-cadastro-usuarios
    network_mode: "host"
    ports:
      - 3001:3001
    environment:
      - ENDERECO_HOST_MQ=${ENDERECO_HOST_MQ}
  
  apostas:
    image: leandroboromualdo/posgraducaopuc:latest
    container_name: sistema-gerenciamento-apostas
    network_mode: "host"
    ports:
      - 3002:3010
    environment:
      - HOST_MQ=${ENDERECO_HOST_MQ}
      - QUEUE_NAME=${DRAW_QUEUE_NAME}
      - EXCHANGE_NOTIFICATIONS_NAME=${NOTIFICATIONS_QUEUE_NAME}
  
  sorteios:
    image: dockerguel/animalbet:latest
    container_name: sistema-sorteios
    network_mode: "host"
    ports:
      - 3003:3003
    environment:
      - HOST_MQ=${ENDERECO_HOST_MQ}